name: Release Obsidian Plugin

env:
  PLUGIN_NAME: obsidian-2-anki

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "18.x"

      - name: Get Version
        id: version
        run: |
          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build
        id: build
        run: |
          npm ci
          npm run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css README.md ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip ${{ env.PLUGIN_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          draft: true
          files: |
            main.js
            manifest.json
            styles.css
            ${{ env.PLUGIN_NAME }}-${{ env.tag }}.zip
